name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run the tests <3
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - name: deps
        run: |
          sudo apt-get install -y libsfml-dev
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install
      - uses: actions/checkout@v2
      - name: generate
        run: cmake -DBUILD_TESTS=ON ..
        working-directory: ./build
      - name: build
        run: make
        working-directory: ./build
      - name: test
        run: ./test/arcpp_test
        working-directory: ./build
